version: "2"

services:
  app:
    build:
      context: .
      dockerfile: docker-files/Dockerfile-app
    networks:
      - password-app-network
    ports:
      - "127.0.0.1:5000:8000"
    volumes:
      - .:/usr/src/app
    working_dir: /tmp
    depends_on:
      - db
    command: gunicorn --bind 0.0.0.0:8000 pofh:wsgi

  db:
    restart: always
    build:
      context: .
      dockerfile: docker-files/Dockerfile-db
    networks:
      - password-app-network
    ports:
      - "127.0.0.1:6379:6379"

networks:
  password-app-network:
    driver: bridge
